[alias] # command aliases
r = "run -- --connect tcp://validator:4004 -vv"

[term]
quiet = false          # whether cargo output is quiet
verbose = true         # whether cargo provides verbose output
